on: 
  push:
#   paths:
#     - .github/repo.yml

jobs:
  github-config:
    runs-on: ubuntu-latest
    name: Apply GitHub config
    environment: CONFIG
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Apply
        uses: "./"
        with:
          github-token: "${{ secrets.GH_TOKEN }}"
